/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com.example.device_jni_PropertiesGet */

#ifndef _Included_com.example.emu_jni_PropertiesGet
#define _Included_com.example.emu_jni_PropertiesGet
#ifdef __cplusplus
extern "C"
{
#endif
    /*
 * Class:     com.example.device_jni_PropertiesGet
 * Method:    native_get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
    JNIEXPORT jstring JNICALL Java_com_example_emu_jni_PropertiesGet_native_1get__Ljava_lang_String_2(JNIEnv *, jclass, jstring);

    /*
 * Class:     com.example.device_jni_PropertiesGet
 * Method:    native_get
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
    JNIEXPORT jstring JNICALL Java_com_example_emu_jni_PropertiesGet_native_1get__Ljava_lang_String_2Ljava_lang_String_2(JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
